kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sirius-cr
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - jobs
      - configmaps
    verbs:
      - delete
      - get
      - list
      - watch
      - update
      - create
      - patch
  - apiGroups: [ "batch", "extensions" ]
    #
    # at the HTTP level, the name of the resource for accessing Job
    # objects is "jobs"
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]