kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sirius-crb
  namespace: sirius
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sirius-cr
subjects:
  - kind: ServiceAccount
    name: sirius-sa
    namespace: sirius