kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sirius-cr
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - update