apiVersion: batch/v1
kind: Job
metadata:
  name: sirius-job
spec:
  template:
    apiVersion: v1
    kind: Pod
    metadata:
      name: sirius
      namespace: sirius
      labels:
        app: sirius
    spec:
      ttlSecondsAfterFinished: 30
      shareProcessNamespace: true
      serviceAccountName: sirius-sa
      containers:
        - name: sirius-b
          image: hyc3z/sirius-b:cuda-10.1-1.5
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: SCHEDULING_POLICY
              value: "default"
            - name: MONITOR_GPU_INTERVAL_PATTERN
              value: "* * * * * ?"
            - name: MONITOR_POLICY_INTERVAL_PATTERN
              value: "0 * * * * ?"
            - name: MEM_MAX_LIMIT
              value: "2147483648"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: false
        - name: sirius-a
          image: hyc3z/sirius-a:cuda-10.1-resnet-1.0
          imagePullPolicy: Always
          env:
            - name: MEM_MAX_LIMIT
              value: "2147483648"
          volumeMounts:
            - name: vcuda
              mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
              readOnly: true
            - name: vcuda-orig
              mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1.orig
              readOnly: true
            - name: vcuda-lib
              mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.430.64
              readOnly: true
            - name: vnvml
              mountPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
              readOnly: true
            - name: vnvml-orig
              mountPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1.orig
              readOnly: true
            - name: vnvml-lib
              mountPath: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.430.64
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      volumes:
        - name: vcuda
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libcuda.so.1
        - name: vcuda-orig
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libcuda.so.1.orig
        - name: vcuda-lib
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libcuda.so.430.64
        - name: vnvml
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libnvidia-ml.so.1
        - name: vnvml-orig
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libnvidia-ml.so.1.orig
        - name: vnvml-lib
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libnvidia-ml.so.430.64
      terminationGracePeriodSeconds: 30
      restartPolicy: Never