apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: development
spec:
  selector:
    matchLabels:
      name: mysql-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name:  MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mysql_data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql_data
          hostPath:
            path: /data/mysql_data

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: development
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 10306
      targetPort: 3306
  selector:
    name: mysql