apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  namespace: default
  labels:
    name: mysql-rc
spec:
  selector:
    name: mysql-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-pod
    spec:
      containers:
        - name: mysql
          image: hyc3z/k8s-web-db:mysql-5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name:  MYSQL_ROOT_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  selector:
   name: mysql-pod
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
