apiVersion: v1
kind: Pod
metadata:
  name: sirius
  namespace: sirius
  labels:
    app: sirius
spec:
  shareProcessNamespace: true
  serviceAccountName: sirius-sa
  containers:
    - name: sirius-b
      image: hyc3z/sirius-b:cuda-10.1-1.0
      imagePullPolicy: Always
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: SCHEDULING_POLICY
          value: "default"
        - name: MONITOR_GPU_INTERVAL_PATTERN
          value: "* * * * * ?"
        - name: MONITOR_POLICY_INTERVAL_PATTERN
          value: "0 * * * * ?"
        - name: MEM_MAX_LIMIT
          value: "2147483648"
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 200Mi
      securityContext:
        privileged: false
    - name: sirius-a
      image: hyc3z/sirius-a:cuda-10.1-resnet-1.0
      imagePullPolicy: Always
      command: ["mv", "/usr/lib/x86_64-linux-gnu/libcuda.so.1", "/usr/lib/x86_64-linux-gnu/libcuda.so.1.orig"]
      env:
        - name: MEM_MAX_LIMIT
          value: "2147483648"
      volumeMounts:
        - name: vcuda
          mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          subPath: libcuda.so.1
          readOnly: true
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      volumes:
        - name: vcuda
          hostPath:
            path: /home/cuda-w-mem-watcher/binaries/10.1/libcuda.so.1
  terminationGracePeriodSeconds: 30
  restartPolicy: Never